apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: todo-lb
          servicePort: 3001
      - path: /api
        backend:
          serviceName: todo-api-service
          servicePort: 8081
