apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: 34.90.98.32.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: todo-lb
              servicePort: 3001
          - path: /api
            backend:
              serviceName: {{ .Values.api.apiName }}
              servicePort: {{ .Values.api.apiPort }}
