apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.ports.port }}
      targetPort: {{ .Values.api.service.ports.targetPort }}
  selector:
    app: {{ .Values.api.labels.app }}
