apiVersion: apps/v1
kind: Deployment
metadata:
 name: todo-ui-deployment
 labels:
  app: todo-ui
spec:
  replicas: 1
  selector:
   matchLabels:
    app: todo-ui
  template:
   metadata:
    labels:
     app: todo-ui
   spec:
    containers:
     - name: todo-ui-container
       image: localhost:32000/todo-ui
       env:
        - name: REACT_APP_API_URL
          value: "http://{{ .Values.api.apiName }}:{{ .Values.apiPort }}"
       ports:
        - containerPort: {{ .Values.ui.webPort }}