apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.api.deployment.name }}
 labels:
  app: {{ .Values.api.labels.app }}
spec:
  replicas: {{ .Values.api.deployment.spec.replicas }}
  selector:
   matchLabels:
    app: {{ .Values.api.labels.app }}
  template:
   metadata:
    labels:
     app: {{ .Values.api.labels.app }}
   spec:
    containers:
     - name: {{ .Values.api.deployment.spec.template.spec.containerName }}
       image: {{ .Values.api.deployment.spec.template.spec.image }}
       env:
        - name: POSTGRESQL_NAME_OVERRIDE
          value: "{{ .Values.postgresql.nameOverride }}"
        - name: POSTGRESQL_PASSWORD
          value: "{{ .Values.postgresql.postgresqlPassword }}"
        - name: POSTGRESQL_USERNAME
          value: "{{ .Values.postgresql.postgresqlUsername }}"
        - name: POSTGRESQL_DATABASE
          value: "{{ .Values.postgresql.postgresqlDatabase }}"
        - name: POSTGRESQL_PERSISTENCE
          value: "{{ .Values.postgresql.persistence.enabled }}"
        - name: POSTGRESQL_REPLICATION
          value: "{{ .Values.postgresql.replication.enabled }}"
        - name: POSTGRESQL_HOST
          value: "{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}"
        - name: POSTGRESQL_PORT
          value: "{{ .Values.postgresql.port }}"
       ports:
        - containerPort: {{ .Values.api.apiPort }}
