apiVersion: apps/v1
kind: Deployment
metadata:
 name: todo-api-deployment
 labels:
  app: todo-api
spec:
  replicas: 1
  selector:
   matchLabels:
    app: todo-api
  template:
   metadata:
    labels:
     app: todo-api
   spec:
    containers:
     - name: todo-api-container
       image: localhost:32000/todo-app:v1
       env:
        - name: POSTGRESQL_NAME_OVERRIDE
          value: "{{ .Values.postgresql.nameOverride }}"
        - name: POSTGRESQL_PASSWORD
          value: "{{ .Values.postgresql.postgresqlPassword }}"
        - name: POSTGRESQL_USERNAME
          value: "{{ .Values.postgresql.postgresqlUsername }}"
        - name: POSTGRESQL_DATABASE
          value: "{{ .Values.postgresql.postgresqlDatabase }}"
        - name: POSTGRESQL_PERSISTENCE
          value: "{{ .Values.postgresql.persistence.enabled }}"
        - name: POSTGRESQL_REPLICATION
          value: "{{ .Values.postgresql.replication.enabled }}"
        - name: POSTGRESQL_HOST
          value: "{{ .Values.postgresql.host }}"
        - name: POSTGRESQL_PORT
          value: "{{ .Values.postgresql.port }}"
       ports:
        - containerPort: 5000