apiVersion: v1
kind: Service
metadata:
  name: todo-ui-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      nodePort: 3000
      port: 8091
      targetPort: 80
  selector:
    app: todo-ui