apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.uicanary.deployment.name }}
 labels:
  app: {{ .Values.uicanary.labels.app }}
  version: {{ .Values.uicanary.labels.version }}
spec:
  replicas: {{ .Values.uicanary.deployment.spec.replicas }}
  selector:
   matchLabels:
    app: {{ .Values.uicanary.labels.app }}
    version: {{ .Values.uicanary.labels.version }}
  template:
   metadata:
    labels:
     app: {{ .Values.uicanary.labels.app }}
     version: {{ .Values.uicanary.labels.version }}
   spec:
    containers:
     - name: {{ .Values.uicanary.deployment.spec.template.spec.containerName }}
       image: {{ .Values.uicanary.deployment.spec.template.spec.image }}
       ports:
        - containerPort: {{ .Values.uicanary.webPort }}
