apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service.name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: {{ .Values.ui.service.ports.nodePort }}
      port: {{ .Values.ui.service.ports.port }}
      targetPort: {{ .Values.ui.service.ports.targetPort }}
  selector:
    app: {{ .Values.ui.labels.app }}
