apiVersion: v1
kind: Service
metadata:
  name: todo-lb
spec:
  selector:
    app: todo-ui
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 3001
      targetPort: 3000
  type: LoadBalancer