apiVersion: v1
kind: Service
metadata:
  name: todo-ui-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 3000
      targetPort: 3000
  selector:
    app: todo-ui