apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.lb.name }}
spec:
  selector:
    app: {{ .Values.ui.labels.app }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.ui.lb.ports.nodePort }}
      port: {{ .Values.ui.lb.ports.port }}
      targetPort: {{ .Values.ui.lb.ports.targetPort }}
  type: LoadBalancer
