postgresql:
  nameOverride: todo-postgres
  postgresqlPassword: writer
  postgresqlUsername: writer
  postgresqlDatabase: todo
  persistence.enabled: true
  replication.enabled: false
  port: 5432
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "4096Mi"
      cpu: "0.25"

apiPort: 8081
webPort: 3000

backend:
  apiName: todo-api-service

